spring:
  devtools:
    restart:
      enabled: false

sms:
  wait: 5000 #5초 MILLISECONDS


logging:
  level:
    root: info
server:
  port: 8081
management:
  endpoint:
    shutdown:
      enabled: true
